- src/redux.js
> Fix create session saga error

- src/App.jsx
> Update James's description

- slack/welcome-message.txt
We've got a Russian Keep channel now, let's include it in the welcome message for our new Russian Keepers :sunglasses:
> Add Russian Keep channel to welcome message

- src/App.jsx
Closes #75 
Updated success message looks like:
> Remove waitlist messaging from slack signup form

- src/App.jsx
- src/css/app.less
- src/css/vars.less
For visual bugs mentioned in [this FD thread](https://www.flowdock.com/app/cardforcoin/keep/threads/WJvG_yuR-O3EmZ__ZUrmzDEXdCJ)
> Fix wall pattern resolution and button placement for hiring section on tablet size

- src/App.jsx
Someone spotted that lendroid.com doesn't work, only www.lendroid.com!
> Fix Lendroid URL

- src/App.jsx
> Shuffle Time: Update site to reflect Piotr's title shift

- slack/welcome-message.txt
> Add Yellowpaper PDF and swap lines a bit

- src/App.jsx
Looking forward to an excellent year!
> Happy New Year 🎉

- src/App.jsx
- src/css/alerts.less
- src/css/nav.less
Also updates banner color.
<details><summary>Screenshots</summary>
</details>
> Update banner copy for stakedrop announcement

- src/App.jsx
- src/PlayingForKeepsTermsContent.js
- Adds some revisions
- Switches out usage of `<Link>` (from react-router-dom) in the footer for `<a>` elements to make sure the pages load from the top of the page
> Update Playing For Keeps Terms

- gatsby-config.js
- gatsby-node.js
- src/components/Announcement.js
- src/components/App.js
- src/components/Header.js
- src/components/index.js
- src/css/alerts.scss
- src/css/header.scss
- src/header/announcement.md
- src/header/nav.md
- static/admin/config.yml
The nav and announcement banner now can be edited in the admin view. Refactors the header a bit to move the `Alert` into the header component from being a child of the `App`, so that we don't have to adjust the `top` positioning based on the content height of the announcement copy like we did previously.
> Make the header and announcement editable by CMS

- src/constants.js
- src/css/home.scss
- src/templates/home-page.js
This section isn't clear on the fact that it's suggested uses rather
than real ones, contains the last link to the (outdated) whitepaper, and
generally isn't up to snuff. Put it to bed for now, pending a greater
rework of the site and its content.
Closes #252 .
> Alas, Poor Apps: Drop Applications section

- src/css/legal.scss
- src/pages/playing-for-keeps-terms.md
- src/templates/legal-page.js
#312 making headlines more consistent with hierarchy and styling
> making headlines more consistent with hierarchy and styling

- .github/workflows/build.yaml
- security.txt
Included at the repository root, and copied into the site root and .well-known
path recommended by RFC8615 during the Actions build.
The security.txt file is PGP signed by me.
> Add security.txt

- src/footer/index.md
> Happy New Year! 🎉

- README.md
Add Development and Deployment sections to the README.
> Add dev docs

- src/components/v2/Grid/Card.js
- src/components/v2/Grid/Grid.js
- src/components/v2/Grid/index.js
- src/css/v2/app.scss
- src/css/v2/banner.scss
- src/css/v2/blog.scss
- src/css/v2/button.scss
- src/css/v2/carousel.scss
- src/css/v2/contact.scss
- src/css/v2/footer.scss
- src/css/v2/grid.scss
- src/css/v2/typography.scss
- src/css/v2/utilities.scss
- src/css/v2/vars.scss
- src/templates/v2-home-page.js
> SRT-13: Landing page styling

- src/components/Contact.js
- static/admin/config.yml
- Fixed build issue in prev PR #358 
- Defines static contents
> [SRT-24] - Data: Landing

- src/css/app.scss
- src/css/faq.scss
- src/templates/faq-page.js
> Feat(UI)/SRT-8: Create faq page

- src/components/FeatureCarousel.js
> Fix lint issue

- src/components/Contact.js
- src/components/EmailForm.js
- src/components/index.js
- src/css/app.scss
- src/css/button.scss
- src/css/home.scss
- src/css/info.scss
- src/pages/info.md
- src/templates/info-page.js
Ticket [#SRT-3](https://scalio.atlassian.net/browse/SRT-3).
- UI styling based on new design
Loom Video: [Info Page](https://www.loom.com/share/f7bef064e9ee46f8a0493b120dcf0659)
Password: keep2021
> feat(UI)/SRT-3: UI styling for Info page

- src/css/press.scss
- src/templates/press-page.js
I have finished the visual part for News-Press Page. The page is responsive.
> Feat(UI)/SRT-6: UI styling for New-Press Page

- src/templates/press-page.js
Fixed lint error in `press-page` component.
> hotfix(lint): fixed lint error in Press page

- src/components/RecommendedCard.js
- src/components/WhyStakeCard.js
- src/templates/stake-page.js
Fixed lint errors in Stake page
> hotfix(lint): fixed lint errors in Stake page

- src/components/Profile.js
- src/css/app.scss
- src/css/blurb.scss
- src/css/profile.scss
- src/css/team.scss
- src/templates/team-page.js
- create team page template and style
> Feat(UI)/SRT-5: Create team page

- src/components/RecommendedCard.js
- src/components/WhyStakeCard.js
Fixed build error related Stake page.
> Hotfix(build): fixed build error in Stake page

- src/components/Contact.js
- src/components/Header.js
- src/components/SummaryGrid.js
- src/css/footer.scss
- src/css/header.scss
- src/css/home.scss
- src/css/page-section.scss
- src/css/typography.scss
- src/templates/home-page.js
- Update layout
- Update styling
- In progress responsiveness
> Feat(UI)/SRT-31: [WIP] General review for Landing page

- src/components/Header.js
Fixed build error related referencing `window` in Header.
> Hotfix(Build): Fixed build error in Header

- src/css/build.scss
- src/css/info.scss
- src/css/page-section.scss
- src/css/press.scss
- src/css/team.scss
- src/templates/build-page.js
- src/templates/press-page.js
- src/templates/stake-page.js
Spacing fixed for landing page and all other pages' hero titles.
> feat(UI)/SRT-34/Landing page and all pages hero title spacing fixed

- src/css/faq.scss
- src/pages/faq.md
- src/templates/faq-page.js
FAQ answers styled and set to actual answers
> feat(UI)/SRT-35/FAQ page answers styled and set to actual answers

- .eslintrc
- src/templates/build-page.js
- src/templates/faq-page.js
- src/templates/stake-page.js
npm run lint passes all tests.
The following snippet is added to .eslintrc file:
"prettier/prettier": [
"error",
{
"endOfLine": "auto"
}
]
Lint spacing rules fixed on build-page, stake-page, faq-page
> Bug/SRT-39: Fix Build Error - Fixed

- src/css/press.scss
- src/templates/press-page.js
Added 2021 to "filter by year" on News-Press page as well as it's active indicator
> Feat(UI)/SRT-36: News-Press

- .prettierrc
- src/components/KeepBlog.js
- src/components/MiniLogoWall.js
- src/components/SummaryGrid.js
- src/css/app.scss
- src/css/contact.scss
- src/css/home.scss
- src/css/keep-blog.scss
- src/css/legal.scss
- src/css/minilogo-grid.scss
- src/css/page-section.scss
- src/css/profile.scss
- src/css/summary-grid.scss
- src/pages/index.md
- src/templates/home-page.js
Ticket: [[SRT-32](https://scalio.atlassian.net/browse/SRT-32)]
- Refactoring layout, styling, and responsiveness in Landing page
Loom Video: [Landing Page](https://www.loom.com/share/55b2620be8154e06be18281f239d5b06) (password: keep2021)
> feat(UI)/SRT-32: General Review Part 2

- .prettierrc
- src/components/FeatureCard.js
- src/components/KeepBlog.js
- src/components/MiniLogoWall.js
- src/components/SummaryGrid.js
- src/css/app.scss
- src/css/contact.scss
- src/css/home.scss
- src/css/keep-blog.scss
- src/css/legal.scss
- src/css/minilogo-grid.scss
- src/css/page-section.scss
- src/css/profile.scss
- src/css/summary-grid.scss
- src/pages/index.md
- src/templates/home-page.js
Ticket: [[SRT-33](https://scalio.atlassian.net/browse/SRT-33)]
- Fixed issue that Info page UI doesn't matched design.
> Bug(UI)/SRT-33: UI Info page

- src/css/press.scss
- src/templates/press-page.js
"Filter by year" on news-press page is fixed and working.
> Feat(UI)/SRT-42: News-Press page filters fixed

- src/css/press.scss
- src/templates/press-page.js
Filters fixed for news press page. isAcitve class added to the filter and UI border-bottom is now persistent
> Feat(UI)/SRT-44: Functionality - News-Press latest coverage

- src/components/Header.js
- src/css/header.scss
Ticket: [SRT-43]
- Header resize by 50% when scrolling down the page
- Change the header's background color with grey alpha when scrolling down the page
Loom Video: [[link](https://www.loom.com/share/8059d2a6b8074cc4848745372f9fd782)] (password: keep2021)
> feat(UI)/SRT-43: Header animation

- package-lock.json
- package.json
- src/templates/home-page.js
Basic parallax implemented with separate elements transition using "Aos" library. Transition time 1 second.
> Feat(UI)/SRT-38: UI Landing page keep solution baseline parallax

- src/css/home.scss
- src/templates/home-page.js
1. Flip effect removed from all backgrounds. 
2. Text transitions fixed in all 3 sections as requested by thesis designer.
3. Black circle in the first section is replaced with gray half-circle
> Feat(UI)/SRT-41: UI Landing page keep solution parallax updates

- src/constants.js
- src/css/header.scss
- src/css/home.scss
- src/templates/home-page.js
Ticket: [[SRT-48](https://scalio.atlassian.net/browse/SRT-48)]
- Remove the bottom grey border
> Hotfix(UI)/SRT-48: Header update

- src/css/home.scss
- src/templates/home-page.js
Fixed parallax effects and colors
> Feat(UI)/SRT-49: UI Landing page keep solution parallax updates 2

- src/templates/home-page.js
Animation on the landing page runs only once.
> Feat(UI)/SRT-62: Keep animation - landing page -  keep solution ui

- src/templates/press-page.js
"All" option added to "filter by year"
> Feat(UI)/SRT-67: Keep ui feedback press-page

- src/pages/build.md
Hero title changed, hero body changed, links fixed on 'library of resources' buttons, links fixed on 'community built' buttons, low resolution images replaced with high resolution images in "community built" section.
> Feat/SRT-67: Keep ui feedback build-page

- src/css/stake-page.scss
Background image set on "banner-business-team" section
> Feat/SRT-65: Keep ui feedback stake-page

- src/css/stake-page.scss
- src/css/team.scss
- src/templates/stake-page.js
- src/templates/team-page.js
Background image implementation refactored
> Feat(UI)/SRT-70: Keep UI feedback stake/team page images

- src/pages/index.md
- src/pages/press.md
- static/admin/config.yml
Ticket: [[SRT-72](https://scalio.atlassian.net/browse/SRT-72)]
- Modified title for blogs in both of Landing and Press page
- Add a "Latest Blog" section to enable add/remove blogs in CMS admin
> feat(Data)/SRT-72: UI Feedback -> All News Create Data Models

- src/components/Button.js
- src/components/FeatureCard.js
- src/templates/stake-page.js
> Feat(UI)/SRT-78: Keep fix build error

- src/components/Header.js
- src/css/alerts.scss
- src/css/blurb.scss
- src/css/button.scss
- src/css/exchanges.scss
- src/css/forms.scss
- src/css/home.scss
- src/css/page-section.scss
- src/css/press.scss
- src/css/profile.scss
- src/css/team.scss
- src/css/typography.scss
- src/templates/home-page.js
Ticket: [[SRT-76](https://scalio.atlassian.net/browse/SRT-76)]
- Fixed the breakpoint for mobile screen
- Fixed the button hover not worked in the Landing page
- Full-width notification in the Landing page for mobile screen
- Adjustment spacing between sections based on design in the Team page
> feat(UI)/SRT-76: General UI Review + Code cleanup

- src/css/header.scss
Underline hover effect restored for navigation items only and removed from dropdown menu items
> Feat(UI)/SRT-80: Keep header menu underline

- src/css/blurb.scss
- src/css/profile.scss
- src/css/team.scss
Ticket: [[SRT-76](https://scalio.atlassian.net/browse/SRT-76)]
- Enhancement UI styling for Team page
> hotfix(UI)/SRT-76: General UI Review - Team page

- src/pages/build.md
- src/pages/info.md
- src/pages/stake.md
Ticket: [SRT-84]
- Links in Join, Stake, and Info pages update from design
> feat(UI)/SRT-84: Links update from Design

- src/pages/press.md
- src/templates/press-page.js
Ticket: [[SRT-85](https://scalio.atlassian.net/browse/SRT-85)]
- Updates news data from the feedback.
> feat(Data)/SRT-85: News data update

- src/pages/index.md
- src/pages/press.md
Ticket: [[SRT-86](https://scalio.atlassian.net/browse/SRT-86)]
- Landing Page: Update “Latest from the Keep Blog” to read as “Featured Coverage”
- News → Press Page: Add 3 articles currently in “Featured Coverage” to the “Latest Coverage” article list and it shows up when the filter is set to 2021.
> hotfix/SRT-86: News update part 2

- src/pages/index.md
- src/pages/stake.md
Update uniswap and balancer links to reference the ETH<>KEEP pair
> Update ex links

- src/components/App.js
- src/components/Contact.js
- src/components/EmailForm.js
- src/components/Header.js
- src/css/app.scss
- src/css/build.scss
- src/css/faq.scss
- src/css/feature-card.scss
- src/css/forms.scss
- src/css/header.scss
- src/css/home.scss
- src/css/info.scss
- src/css/page-section.scss
- src/css/profile.scss
- src/templates/build-page.js
- src/templates/faq-page.js
- src/templates/info-page.js
- src/templates/press-page.js
- src/templates/team-page.js
Ticket: [[SRT-87](https://scalio.atlassian.net/browse/SRT-87)]
- Logo: Logo on mobile is pushed down by banner
- Header: Remove drop-shadow container around all sub-navigation items on mobile
- Team page: Team member name's line-height to be smaller
- Info page: Tbtc “check it out” button to be full-width on mobile
- Stake page: Logos for staking providers to be more margin on both of Desktop and Mobile screen
- Home page: Email validation error message shows under the input and update the success message content for subsribed
- Join and Info page: minor changes for image showing as fit on mobile
> Fix(UI)/SRT-87: UI feedback update 3

- src/components/LoadingBlocks.js
- src/components/SlideInAnimation.js
- src/css/app.scss
- src/css/loading-blocks.scss
- src/css/slide-in-animation.scss
- src/css/vars.scss
- src/templates/home-page.js
Closes: #445 
We are getting rid of the "loading..." text from home page of the keep website and replacing it with the animation
https://user-images.githubusercontent.com/40306834/120789121-7744d080-c531-11eb-9857-5b1a064e5fbd.mov
> APY loading fix

- src/components/MiniLogoWall.js
- src/footer/index.md
- src/pages/press.md
- src/templates/press-page.js
- static/admin/config.yml
> Update links and CMS config

- src/footer/index.md
Updating Governance link to link to the forum
> Update Footer “footer_nav”

- src/header/nav.md
Updating header navigation to include "Audits" link in the "About" dropdown
> Update Header “header_nav”

- src/pages/index.md
Changes CTA to /join URL instead of /build
> Updates CTA to /join

- src/pages/faq.md
Updating copy of some FAQ questions. Fixing link styles for the FAQ responses. Reorganizing a few questions in the order of the FAQ.
> Fixing link styles in the FAQ section

- src/pages/index.md
Removing extra colon ":" from exchanges section
> Removing extra colon ":" from exchanges section

- src/lib/liquidity-rewards/liquidity-rewards.js
We created a new Infura endpoint for Keep website. This commit will
switch keep.network website to it.
> Replace the Infura link with the new one

- src/hooks/useLiquidityRewardsAPY.js
Removes APY calculation for KEEP/ETH pool
> Remove KEEP/ETH pool

- src/templates/home-page.js
This PR remove TBTC-v2/Saddle-v2 pool from the keep website.
> Remove TBTC-v2/Saddle-V2 pool
